/* WebGL shaders for the live beauty effect. GLSL ES 1.00 (works on WebGL1/WebGL2). ES module. */

export var BEAUTY_VERT = [
  'attribute vec2 aPos;',
  'varying vec2 vUv;',
  'void main(){',
  '  vUv = aPos * 0.5 + 0.5;',
  '  gl_Position = vec4(aPos, 0.0, 1.0);',
  '}'
].join('\n');

/* Separable bilateral-ish blur: run once per axis (uDir). uFrame is the full-res frame texture. */
export var BEAUTY_BLUR_FRAG = [
  'precision highp float;',
  'varying vec2 vUv;',
  'uniform sampler2D uFrame;',
  'uniform vec2 uTexel;',
  'uniform vec2 uDir;',
  'uniform float uSigma;',
  'uniform float uEdge;',
  'void main(){',
  '  vec3 c = texture2D(uFrame, vUv).rgb;',
  '  vec3 acc = c;',
  '  float wsum = 1.0;',
  '  vec2 o1 = uDir * uTexel * 1.0;',
  '  vec2 o2 = uDir * uTexel * 2.0;',
  '  vec2 o4 = uDir * uTexel * 4.0;',
  '  vec2 o8 = uDir * uTexel * 8.0;',
  '  float s2 = 2.0 * uSigma * uSigma;',
  '  vec3 c1a, c1b;',
  '  float w;',
  '  c1a = texture2D(uFrame, vUv + o1).rgb;',
  '  c1b = texture2D(uFrame, vUv - o1).rgb;',
  '  w = uEdge * dot(c - c1a, c - c1a);',
  '  w = exp(-w);',
  '  acc += c1a * w; wsum += w;',
  '  w = uEdge * dot(c - c1b, c - c1b);',
  '  w = exp(-w);',
  '  acc += c1b * w; wsum += w;',
  '  c1a = texture2D(uFrame, vUv + o2).rgb;',
  '  c1b = texture2D(uFrame, vUv - o2).rgb;',
  '  w = exp(-1.0 / s2) * exp(-uEdge * dot(c - c1a, c - c1a));',
  '  acc += c1a * w; wsum += w;',
  '  w = exp(-1.0 / s2) * exp(-uEdge * dot(c - c1b, c - c1b));',
  '  acc += c1b * w; wsum += w;',
  '  c1a = texture2D(uFrame, vUv + o4).rgb;',
  '  c1b = texture2D(uFrame, vUv - o4).rgb;',
  '  w = exp(-4.0 / s2) * exp(-uEdge * dot(c - c1a, c - c1a));',
  '  acc += c1a * w; wsum += w;',
  '  w = exp(-4.0 / s2) * exp(-uEdge * dot(c - c1b, c - c1b));',
  '  acc += c1b * w; wsum += w;',
  '  c1a = texture2D(uFrame, vUv + o8).rgb;',
  '  c1b = texture2D(uFrame, vUv - o8).rgb;',
  '  w = exp(-16.0 / s2) * exp(-uEdge * dot(c - c1a, c - c1a));',
  '  acc += c1a * w; wsum += w;',
  '  w = exp(-16.0 / s2) * exp(-uEdge * dot(c - c1b, c - c1b));',
  '  acc += c1b * w; wsum += w;',
  '  gl_FragColor = vec4(acc / wsum, 1.0);',
  '}'
].join('\n');

/* Final composite: mixes blurred base with original driven by skin/eyes/teeth masks and settings. */
export var BEAUTY_COMPOSE_FRAG = [
  'precision highp float;',
  'varying vec2 vUv;',
  'uniform sampler2D uFrame;',
  'uniform sampler2D uBase;',
  'uniform sampler2D uMask;',
  'uniform float uBeauty;',
  'uniform float uSmooth;',
  'uniform float uRetouch;',
  'uniform float uEyes;',
  'uniform float uTeeth;',
  'uniform float uLight;',
  'uniform float uUniform;',
  'void main(){',
  '  vec3 orig = texture2D(uFrame, vUv).rgb;',
  '  vec3 base = texture2D(uBase, vUv).rgb;',
  '  vec3 m = texture2D(uMask, vUv).rgb;',
  '  float skin = clamp(m.r, 0.0, 1.0);',
  '  float eyes = clamp(m.g, 0.0, 1.0);',
  '  float teeth = clamp(m.b, 0.0, 1.0);',
  '  float master = clamp(uBeauty, 0.0, 1.0);',
  '  if (master <= 0.0001) { gl_FragColor = vec4(orig, 1.0); return; }',
  '  float d = length(orig - base);',
  '  float edg = smoothstep(0.015, 0.10, d);',
  '  float keep = 1.0 - 0.85 * edg;',
  '  vec3 col = orig;',
  '  float sm = clamp(master * uSmooth * skin * keep, 0.0, 1.0);',
  '  col = mix(col, base, sm);',
  '  float rt = clamp(master * uRetouch * skin * (1.0 - edg) * 0.6, 0.0, 1.0);',
  '  col = mix(col, base, rt);',
  '  float ey = master * uEyes * eyes;',
  '  if (ey > 0.001) {',
  '    vec3 lift = clamp(col * 1.08 + vec3(0.02), 0.0, 1.0);',
  '    col = mix(col, lift, ey * 0.4);',
  '    col = clamp(col + (orig - col) * ey * 0.55, 0.0, 1.0);',
  '  }',
  '  float te = master * uTeeth * teeth;',
  '  if (te > 0.001) {',
  '    vec3 wht = clamp(col * 0.55 + 0.45, 0.0, 1.0);',
  '    col = mix(col, wht, te * 0.5);',
  '  }',
  '  float li = master * uLight * skin;',
  '  if (li > 0.001) {',
  '    float lum = dot(col, vec3(0.299, 0.587, 0.114));',
  '    float wl = li * (0.55 + 0.45 * (1.0 - min(lum * 1.6, 1.0)));',
  '    col = clamp(col * (1.0 + 0.18 * wl), 0.0, 1.0);',
  '    col = clamp(col + vec3(0.02 * wl), 0.0, 1.0);',
  '  }',
  '  float un = clamp(master * uUniform * skin * (1.0 - edg), 0.0, 1.0);',
  '  col = mix(col, base, un * 0.35);',
  '  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);',
  '}'
].join('\n');